/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class AdminModulePanel1 extends javax.swing.JPanel {

    /**
     * Creates new form STModulePanel
     */
    public AdminModulePanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleHomePage = new javax.swing.JPanel();
        moduleName = new javax.swing.JLabel();
        moduleYear = new javax.swing.JLabel();
        moduleAction = new javax.swing.JLabel();
        moduleScrollPane = new javax.swing.JScrollPane();
        moduleContainer = new javax.swing.JPanel();
        Modules = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        Department = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(910, 630));
        setMinimumSize(new java.awt.Dimension(910, 630));
        setLayout(new java.awt.CardLayout());

        moduleHomePage.setBackground(new java.awt.Color(255, 255, 255));
        moduleHomePage.setMinimumSize(new java.awt.Dimension(910, 630));
        moduleHomePage.setPreferredSize(new java.awt.Dimension(910, 630));

        moduleName.setBackground(new java.awt.Color(255, 51, 51));
        moduleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleName.setText("Module Name");
        moduleName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        moduleName.setMaximumSize(new java.awt.Dimension(290, 40));
        moduleName.setMinimumSize(new java.awt.Dimension(290, 40));
        moduleName.setOpaque(true);
        moduleName.setPreferredSize(new java.awt.Dimension(290, 40));

        moduleYear.setBackground(new java.awt.Color(255, 51, 51));
        moduleYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleYear.setText("Year");
        moduleYear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        moduleYear.setOpaque(true);

        moduleAction.setBackground(new java.awt.Color(255, 51, 51));
        moduleAction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleAction.setText("Action");
        moduleAction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        moduleAction.setOpaque(true);

        moduleScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        moduleScrollPane.setPreferredSize(new java.awt.Dimension(890, 450));

        moduleContainer.setBackground(new java.awt.Color(255, 255, 255));
        moduleContainer.setPreferredSize(new java.awt.Dimension(890, 578));
        moduleContainer.setLayout(new javax.swing.BoxLayout(moduleContainer, javax.swing.BoxLayout.Y_AXIS));
        moduleScrollPane.setViewportView(moduleContainer);

        Modules.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Modules.setForeground(new java.awt.Color(196, 0, 98));
        Modules.setText(" Modules");

        addBtn.setText("ADD");
        addBtn.addActionListener(this::addBtnActionPerformed);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Department.addActionListener(this::DepartmentActionPerformed);

        javax.swing.GroupLayout moduleHomePageLayout = new javax.swing.GroupLayout(moduleHomePage);
        moduleHomePage.setLayout(moduleHomePageLayout);
        moduleHomePageLayout.setHorizontalGroup(
            moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleHomePageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(moduleHomePageLayout.createSequentialGroup()
                        .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moduleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(moduleHomePageLayout.createSequentialGroup()
                                .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(moduleAction, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(15, 15, 15))
                    .addGroup(moduleHomePageLayout.createSequentialGroup()
                        .addComponent(Modules, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(184, 184, 184))))
            .addGroup(moduleHomePageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        moduleHomePageLayout.setVerticalGroup(
            moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleHomePageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modules, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleAction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(moduleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(moduleHomePage, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JLabel Modules;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel moduleAction;
    private javax.swing.JPanel moduleContainer;
    private javax.swing.JPanel moduleHomePage;
    private javax.swing.JLabel moduleName;
    private javax.swing.JScrollPane moduleScrollPane;
    private javax.swing.JLabel moduleYear;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JPanel getModuleContainer()
    {
    return moduleContainer;
    }
}
