/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;

/**
 *
 * @author NITRO
 */
public class AdminDashboardPanel extends DashboardPanel {
    private final Enroll enrollPanel;
    private final AdminProfile adminProfile;

    public Management getManagement() {
        return managementView;
    }

    private final Management managementView;

    public AdminModulePanel getModulePanel() {
        return adminModulePanel;
    }

    private final AdminModulePanel adminModulePanel;

    public ModuleDisplay getModuleDisplay() {
        return moduleDisplay;
    }

    private final ModuleDisplay moduleDisplay;

    public AdminNoticePanel getNoticePanel() {
        return adminNoticePanel;
    }

    private final AdminNoticePanel adminNoticePanel;

    @Override
    public JPanel getProfilePanel() {
        return adminProfile;
    }

    public AdminDashboardPanel() {
        super();
        initComponents();
        componentList.add(new MenuItems(logo));
        componentList.add(new MenuItems(name));
        componentList.add(new MenuGap(110));
        componentList.add(new MenuItems(profile));
        componentList.add(new MenuItems(module));
        componentList.add(new MenuItems(attendance));
        componentList.add(new MenuItems(notice));


        javax.swing.JButton enroll = new javax.swing.JButton();
        buttonDecorator(enroll,"Enroll");
        componentList.add(new MenuItems(enroll));

        javax.swing.JButton management = new javax.swing.JButton();
        buttonDecorator(management,"Management");
        componentList.add(new MenuItems(management));

        componentList.add(new MenuItems(logout));


        enrollPanel= new Enroll();
        adminProfile = new AdminProfile();
        adminModulePanel= new AdminModulePanel();
        moduleDisplay= new ModuleDisplay();
        adminNoticePanel= new AdminNoticePanel();
        managementView = new Management();
        contentPanel.add(adminProfile,"Profile");
        contentPanel.add(enrollPanel, "Enroll");
        contentPanel.add(adminModulePanel,"Module");
        contentPanel.add(moduleDisplay,"ModuleDisplay");
        contentPanel.add(managementView,"Management");
        contentPanel.add(adminNoticePanel,"Notice");




        
        super.menuBuilder(componentList);
        
        javax.swing.GroupLayout layout =(javax.swing.GroupLayout) this.getLayout();
        layout.setHorizontalGroup(
            layout.createSequentialGroup()
            .addComponent(menuPanel)
            .addComponent(contentPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
             .addComponent(menuPanel)
            .addComponent(contentPanel)
            
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(1120, 630));
        setMinimumSize(new java.awt.Dimension(1120, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables

   public Enroll getEnrollPanel()
   {
       return enrollPanel;
   } // End of variables declaration//GEN-END:variables
}
