/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;



/**
 *
 * @author NITRO
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        loginBtn4 = new javax.swing.JButton();
        loginBtn8 = new javax.swing.JButton();
        loginBtn10 = new javax.swing.JButton();
        menu2 = new view.Menu();
        profile = new javax.swing.JButton();
        module = new javax.swing.JButton();
        attendance = new javax.swing.JButton();
        enroll = new javax.swing.JButton();
        management = new javax.swing.JButton();
        App = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();
        routine = new javax.swing.JButton();
        notice1 = new javax.swing.JButton();

        jButton4.setText("jButton1");

        jButton1.setText("jButton1");

        loginBtn4.setBackground(new java.awt.Color(69, 104, 220));
        loginBtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn4.setText("APP");
        loginBtn4.addActionListener(this::loginBtn4ActionPerformed);

        loginBtn8.setBackground(new java.awt.Color(69, 104, 220));
        loginBtn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginBtn8.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn8.setText("Profile");
        loginBtn8.addActionListener(this::loginBtn8ActionPerformed);

        loginBtn10.setBackground(new java.awt.Color(69, 104, 220));
        loginBtn10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginBtn10.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn10.setText("Profile");
        loginBtn10.addActionListener(this::loginBtn10ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        menu2.setMinimumSize(new java.awt.Dimension(250, 471));
        menu2.setPreferredSize(new java.awt.Dimension(280, 471));

        profile.setBackground(new java.awt.Color(69, 104, 220));
        profile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.addActionListener(this::profileActionPerformed);

        module.setBackground(new java.awt.Color(69, 104, 220));
        module.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        module.setForeground(new java.awt.Color(255, 255, 255));
        module.setText("Module");
        module.addActionListener(this::moduleActionPerformed);

        attendance.setBackground(new java.awt.Color(176, 108, 179));
        attendance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        attendance.setForeground(new java.awt.Color(255, 255, 255));
        attendance.setText("Attendance");
        attendance.addActionListener(this::attendanceActionPerformed);

        enroll.setBackground(new java.awt.Color(176, 106, 179));
        enroll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enroll.setForeground(new java.awt.Color(255, 255, 255));
        enroll.setText("Enroll");
        enroll.addActionListener(this::enrollActionPerformed);

        management.setBackground(new java.awt.Color(176, 106, 179));
        management.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        management.setForeground(new java.awt.Color(255, 255, 255));
        management.setText("Management");
        management.addActionListener(this::managementActionPerformed);

        App.setBackground(new java.awt.Color(69, 104, 220));
        App.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        App.setText("APP");
        App.addActionListener(this::AppActionPerformed);

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(App, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(App, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        logout.setBackground(new java.awt.Color(69, 104, 220));
        logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LogOut");
        logout.addActionListener(this::logoutActionPerformed);

        routine.setBackground(new java.awt.Color(69, 104, 220));
        routine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        routine.setForeground(new java.awt.Color(255, 255, 255));
        routine.setText("Routine");
        routine.addActionListener(this::routineActionPerformed);

        notice1.setBackground(new java.awt.Color(176, 108, 179));
        notice1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice1.setForeground(new java.awt.Color(255, 255, 255));
        notice1.setText("Notice");
        notice1.addActionListener(this::notice1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(notice1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notice1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleActionPerformed

    private void attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceActionPerformed

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollActionPerformed

    private void loginBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4ActionPerformed

    private void managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managementActionPerformed

    private void AppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void loginBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8ActionPerformed

    private void routineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routineActionPerformed

    private void loginBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn10ActionPerformed

    private void notice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notice1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton App;
    private javax.swing.JButton attendance;
    private javax.swing.JButton enroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginBtn10;
    private javax.swing.JButton loginBtn4;
    private javax.swing.JButton loginBtn8;
    private javax.swing.JButton logout;
    private javax.swing.JButton management;
    private view.Menu menu2;
    private javax.swing.JButton module;
    private javax.swing.JButton notice1;
    private javax.swing.JButton profile;
    private javax.swing.JButton routine;
    // End of variables declaration//GEN-END:variables

   
    }

