/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class Enroll extends javax.swing.JPanel {
    private final StudentEnroll studentEnroll;
    private final TeacherEnroll teacherEnroll;
    private final AdminEnroll adminEnroll;

    public Enroll() {
        initComponents();
        studentEnroll = new StudentEnroll();
        teacherEnroll= new TeacherEnroll();
        adminEnroll= new AdminEnroll();
        enrollContentPanel.add(studentEnroll,"Student");
        enrollContentPanel.add(teacherEnroll,"Teacher");
        enrollContentPanel.add(adminEnroll,"Admin");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userType = new javax.swing.JComboBox<>();
        enrollContentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        userType.setBackground(new java.awt.Color(255, 255, 255));
        userType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student","Teacher","Admin" }));
        userType.setFocusable(false);
        userType.setOpaque(true);

        enrollContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        enrollContentPanel.setPreferredSize(new java.awt.Dimension(840, 510));
        enrollContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enrollContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enrollContentPanel;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
    public JComboBox<String> getUserType() {
        return userType;
    }

    public JPanel getEnrollContentPanel()
    {
        return enrollContentPanel;
    }

    public void addUserTypeActionListener(ActionListener actionListener)
    {
        userType.addActionListener(actionListener);
    }

    public StudentEnroll getStudentEnroll() {
        return studentEnroll;
    }

    public AdminEnroll getAdminEnroll() {
        return adminEnroll;
    }

    public TeacherEnroll getTeacherEnroll() {
        return teacherEnroll;
    }



}
