/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class Management extends javax.swing.JPanel {

    /**
     * Creates new form Management
     */
    public Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        Teacher = new javax.swing.JPanel();
        teacherFirstNameText = new javax.swing.JTextField();
        teacherGender = new javax.swing.JComboBox<>();
        teacherContactLabel = new javax.swing.JLabel();
        teacherSelectLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        teacherIdTextField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        loadTeacherDataBtn = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        teacherUpdateBtn = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        teacherLastNameText = new javax.swing.JTextField();
        teacherEmailText = new javax.swing.JTextField();
        teacherAddressText = new javax.swing.JTextField();
        teacherContactText = new javax.swing.JTextField();
        teacherDepartmentLabel = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        teacherDepartment = new javax.swing.JComboBox<>();
        teacherFirstNameLabel = new javax.swing.JLabel();
        teacherLastNameLabel = new javax.swing.JLabel();
        teacherGenderLabel = new javax.swing.JLabel();
        teacherEmailLabel = new javax.swing.JLabel();
        teacherAddressLabel = new javax.swing.JLabel();
        Student = new javax.swing.JPanel();
        studentEmailLabel = new javax.swing.JLabel();
        studentAddressLabel = new javax.swing.JLabel();
        studentContactLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        studentLastNameText = new javax.swing.JTextField();
        studentEmailText = new javax.swing.JTextField();
        studentAddressText = new javax.swing.JTextField();
        studentContactText = new javax.swing.JTextField();
        studentCourseLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        studentBatchLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        studentCourseSelect = new javax.swing.JComboBox<>();
        studentBatchSelect = new javax.swing.JComboBox<>();
        studentFirstNameLabel = new javax.swing.JLabel();
        studentLastNameLabel = new javax.swing.JLabel();
        studentGenderLabel = new javax.swing.JLabel();
        studentFirstNameText = new javax.swing.JTextField();
        studentGenderSelect = new javax.swing.JComboBox<>();
        studentSelectLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        loadStudentDataBtn = new javax.swing.JButton();
        studentUpdateBtn = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        studentFirstNameText1 = new javax.swing.JTextField();
        studentFirstNameText2 = new javax.swing.JTextField();
        studentGenderLabel1 = new javax.swing.JLabel();
        studentGenderSelect1 = new javax.swing.JComboBox<>();
        studentEmailLabel1 = new javax.swing.JLabel();
        studentEmailText1 = new javax.swing.JTextField();
        studentAddressLabel1 = new javax.swing.JLabel();
        studentEmailText2 = new javax.swing.JTextField();
        studentContactLabel1 = new javax.swing.JLabel();
        studentEmailText3 = new javax.swing.JTextField();
        genderLabel1 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        studentSelectLabel1 = new javax.swing.JLabel();
        studentIdTextField1 = new javax.swing.JTextField();
        loadStudentDataBtn1 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(910, 630));
        setMinimumSize(new java.awt.Dimension(910, 630));

        teacherFirstNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherFirstNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherFirstNameText.addActionListener(this::teacherFirstNameTextActionPerformed);

        teacherGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
        teacherGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherGender.setFocusable(false);
        teacherGender.setOpaque(true);
        teacherGender.setRequestFocusEnabled(false);
        teacherGender.addActionListener(this::teacherGenderActionPerformed);

        teacherContactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherContactLabel.setText("Contact");

        teacherSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherSelectLabel.setText("Enter Teacher Id:");

        teacherIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        loadTeacherDataBtn.setBackground(new java.awt.Color(51, 51, 51));
        loadTeacherDataBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadTeacherDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        loadTeacherDataBtn.setText("Load Data");
        loadTeacherDataBtn.setFocusPainted(false);

        teacherUpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
        teacherUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        teacherUpdateBtn.setText("Update");
        teacherUpdateBtn.setFocusPainted(false);

        teacherLastNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherLastNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherEmailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherEmailText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherAddressText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherAddressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherContactText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherContactText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherContactText.addActionListener(this::teacherContactTextActionPerformed);

        teacherDepartmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherDepartmentLabel.setText("Department");

        teacherDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentCourseSelect"
            + "" }));
teacherDepartment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
teacherDepartment.setFocusable(false);
teacherDepartment.setOpaque(true);
teacherDepartment.setRequestFocusEnabled(false);
teacherDepartment.addActionListener(this::teacherDepartmentActionPerformed);

teacherFirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherFirstNameLabel.setText("FIrst Name");

teacherLastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherLastNameLabel.setText("Last Name");

teacherGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherGenderLabel.setText("Gender");

teacherEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherEmailLabel.setText("Email");

teacherAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherAddressLabel.setText("Address");

javax.swing.GroupLayout TeacherLayout = new javax.swing.GroupLayout(Teacher);
Teacher.setLayout(TeacherLayout);
TeacherLayout.setHorizontalGroup(
    TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(TeacherLayout.createSequentialGroup()
        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addComponent(teacherFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(314, 314, 314)
                            .addComponent(teacherLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(teacherAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(310, 310, 310)
                            .addComponent(teacherContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator10)
                                .addComponent(teacherLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TeacherLayout.createSequentialGroup()
                        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(teacherDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacherAddressText)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TeacherLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherContactText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))))
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(teacherSelectLabel)
                .addGap(18, 18, 18)
                .addComponent(teacherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadTeacherDataBtn))
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(teacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(54, Short.MAX_VALUE))
    );
    TeacherLayout.setVerticalGroup(
        TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherSelectLabel)
                .addComponent(teacherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadTeacherDataBtn))
            .addGap(30, 30, 30)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherFirstNameLabel)
                .addComponent(teacherLastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherGenderLabel)
                .addComponent(teacherEmailLabel))
            .addGap(12, 12, 12)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherAddressLabel)
                .addGroup(TeacherLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(teacherContactLabel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(23, 23, 23)
            .addComponent(teacherDepartmentLabel)
            .addGap(3, 3, 3)
            .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(teacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(44, Short.MAX_VALUE))
    );

    tabbedPane.addTab("tab2", Teacher);

    Student.setBackground(new java.awt.Color(255, 255, 255));

    studentEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailLabel.setText("Email");

    studentAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentAddressLabel.setText("Address");

    studentContactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentContactLabel.setText("Contact");

    studentLastNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentLastNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentEmailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentAddressText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentAddressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentContactText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentContactText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentContactText.addActionListener(this::studentContactTextActionPerformed);

    studentCourseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentCourseLabel.setText("Course");

    studentBatchLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentBatchLabel.setText("Batch");

    studentCourseSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentCourseSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentCourseSelect"
        + "" }));
studentCourseSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentCourseSelect.setFocusable(false);
studentCourseSelect.setOpaque(true);
studentCourseSelect.setRequestFocusEnabled(false);
studentCourseSelect.addActionListener(this::studentCourseSelectActionPerformed);

studentBatchSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentBatchSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentBatchSelect"
+ "" }));
studentBatchSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentBatchSelect.setFocusable(false);
studentBatchSelect.setOpaque(true);
studentBatchSelect.setRequestFocusEnabled(false);
studentBatchSelect.addActionListener(this::studentBatchSelectActionPerformed);

studentFirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentFirstNameLabel.setText("FIrst Name");

studentLastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentLastNameLabel.setText("Last Name");

studentGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentGenderLabel.setText("Gender");

studentFirstNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentFirstNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentFirstNameText.addActionListener(this::studentFirstNameTextActionPerformed);

studentGenderSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentGenderSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
studentGenderSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentGenderSelect.setFocusable(false);
studentGenderSelect.setOpaque(true);
studentGenderSelect.setRequestFocusEnabled(false);
studentGenderSelect.addActionListener(this::studentGenderSelectActionPerformed);

studentSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentSelectLabel.setText("Enter Student Id:");

studentIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

loadStudentDataBtn.setBackground(new java.awt.Color(51, 51, 51));
loadStudentDataBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
loadStudentDataBtn.setForeground(new java.awt.Color(255, 255, 255));
loadStudentDataBtn.setText("Load Data");
loadStudentDataBtn.setFocusPainted(false);

studentUpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
studentUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
studentUpdateBtn.setText("Update");
studentUpdateBtn.setFocusPainted(false);

javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
Student.setLayout(StudentLayout);
StudentLayout.setHorizontalGroup(
    StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(StudentLayout.createSequentialGroup()
        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addComponent(studentFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(314, 314, 314)
                            .addComponent(studentLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(studentAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(310, 310, 310)
                            .addComponent(studentContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(studentLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentCourseSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentAddressText)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentBatchSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, 384, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentBatchLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentContactText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)))))
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(studentSelectLabel)
                .addGap(18, 18, 18)
                .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadStudentDataBtn))
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(54, Short.MAX_VALUE))
    );
    StudentLayout.setVerticalGroup(
        StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentSelectLabel)
                .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadStudentDataBtn))
            .addGap(30, 30, 30)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentFirstNameLabel)
                .addComponent(studentLastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentGenderLabel)
                .addComponent(studentEmailLabel))
            .addGap(12, 12, 12)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentAddressLabel)
                .addGroup(StudentLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(studentContactLabel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
                    .addComponent(studentCourseLabel)
                    .addGap(3, 3, 3)
                    .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentCourseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentBatchSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
                    .addComponent(studentBatchLabel)
                    .addGap(51, 51, 51)))
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(46, Short.MAX_VALUE))
    );

    tabbedPane.addTab("tab1", Student);

    firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    firstNameLabel.setText("FIrst Name");

    lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lastNameLabel.setText("Last Name");

    studentFirstNameText1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentFirstNameText1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentFirstNameText1.addActionListener(this::studentFirstNameText1ActionPerformed);

    studentFirstNameText2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentFirstNameText2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentFirstNameText2.addActionListener(this::studentFirstNameText2ActionPerformed);

    studentGenderLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentGenderLabel1.setText("Gender");

    studentGenderSelect1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentGenderSelect1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
    studentGenderSelect1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentGenderSelect1.setFocusable(false);
    studentGenderSelect1.setOpaque(true);
    studentGenderSelect1.setRequestFocusEnabled(false);
    studentGenderSelect1.addActionListener(this::studentGenderSelect1ActionPerformed);

    studentEmailLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailLabel1.setText("Email");

    studentEmailText1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailText1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentAddressLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentAddressLabel1.setText("Address");

    studentEmailText2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailText2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentContactLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentContactLabel1.setText("Contact");

    studentEmailText3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailText3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentEmailText3.addActionListener(this::studentEmailText3ActionPerformed);

    genderLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    genderLabel1.setText("Department");

    department.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
    department.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    department.setFocusable(false);
    department.setOpaque(true);
    department.setRequestFocusEnabled(false);
    department.addActionListener(this::departmentActionPerformed);

    update.setBackground(new java.awt.Color(0, 0, 0));
    update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    update.setForeground(new java.awt.Color(255, 255, 255));
    update.setText("Update");
    update.addActionListener(this::updateActionPerformed);

    studentSelectLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentSelectLabel1.setText("Enter Admin Id:");

    studentIdTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    loadStudentDataBtn1.setBackground(new java.awt.Color(51, 51, 51));
    loadStudentDataBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadStudentDataBtn1.setForeground(new java.awt.Color(255, 255, 255));
    loadStudentDataBtn1.setText("Load Data");
    loadStudentDataBtn1.setFocusPainted(false);

    javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
    Admin.setLayout(AdminLayout);
    AdminLayout.setHorizontalGroup(
        AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AdminLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentFirstNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentGenderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentGenderSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmailText2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(109, 109, 109)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(studentEmailText3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentContactLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmailText1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentFirstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(studentSelectLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(studentIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(loadStudentDataBtn1)))
            .addContainerGap(26, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(366, 366, 366))
    );
    AdminLayout.setVerticalGroup(
        AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AdminLayout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentSelectLabel1)
                .addComponent(studentIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadStudentDataBtn1))
            .addGap(34, 34, 34)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(firstNameLabel)
                .addComponent(lastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentFirstNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentFirstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentGenderLabel1)
                        .addComponent(studentEmailLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentGenderSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmailText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentAddressLabel1)
                        .addComponent(studentContactLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentEmailText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmailText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24)
            .addComponent(genderLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(87, 87, 87))
    );

    tabbedPane.addTab("tab3", Admin);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabbedPane)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void studentCourseSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCourseSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentCourseSelectActionPerformed

    private void studentBatchSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBatchSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentBatchSelectActionPerformed

    private void studentFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFirstNameTextActionPerformed

    private void studentGenderSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGenderSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentGenderSelectActionPerformed

    private void studentContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentContactTextActionPerformed

    private void teacherFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherFirstNameTextActionPerformed

    private void teacherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherGenderActionPerformed

    private void teacherContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherContactTextActionPerformed

    private void teacherDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherDepartmentActionPerformed

    private void studentFirstNameText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFirstNameText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFirstNameText2ActionPerformed

    private void studentFirstNameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFirstNameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFirstNameText1ActionPerformed

    private void studentGenderSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGenderSelect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentGenderSelect1ActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void studentEmailText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailText3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel Teacher;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton loadStudentDataBtn;
    private javax.swing.JButton loadStudentDataBtn1;
    private javax.swing.JButton loadTeacherDataBtn;
    private javax.swing.JLabel studentAddressLabel;
    private javax.swing.JLabel studentAddressLabel1;
    private javax.swing.JTextField studentAddressText;
    private javax.swing.JLabel studentBatchLabel;
    private javax.swing.JComboBox<String> studentBatchSelect;
    private javax.swing.JLabel studentContactLabel;
    private javax.swing.JLabel studentContactLabel1;
    private javax.swing.JTextField studentContactText;
    private javax.swing.JLabel studentCourseLabel;
    private javax.swing.JComboBox<String> studentCourseSelect;
    private javax.swing.JLabel studentEmailLabel;
    private javax.swing.JLabel studentEmailLabel1;
    private javax.swing.JTextField studentEmailText;
    private javax.swing.JTextField studentEmailText1;
    private javax.swing.JTextField studentEmailText2;
    private javax.swing.JTextField studentEmailText3;
    private javax.swing.JLabel studentFirstNameLabel;
    private javax.swing.JTextField studentFirstNameText;
    private javax.swing.JTextField studentFirstNameText1;
    private javax.swing.JTextField studentFirstNameText2;
    private javax.swing.JLabel studentGenderLabel;
    private javax.swing.JLabel studentGenderLabel1;
    private javax.swing.JComboBox<String> studentGenderSelect;
    private javax.swing.JComboBox<String> studentGenderSelect1;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JTextField studentIdTextField1;
    private javax.swing.JLabel studentLastNameLabel;
    private javax.swing.JTextField studentLastNameText;
    private javax.swing.JLabel studentSelectLabel;
    private javax.swing.JLabel studentSelectLabel1;
    private javax.swing.JButton studentUpdateBtn;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel teacherAddressLabel;
    private javax.swing.JTextField teacherAddressText;
    private javax.swing.JLabel teacherContactLabel;
    private javax.swing.JTextField teacherContactText;
    private javax.swing.JComboBox<String> teacherDepartment;
    private javax.swing.JLabel teacherDepartmentLabel;
    private javax.swing.JLabel teacherEmailLabel;
    private javax.swing.JTextField teacherEmailText;
    private javax.swing.JLabel teacherFirstNameLabel;
    private javax.swing.JTextField teacherFirstNameText;
    private javax.swing.JComboBox<String> teacherGender;
    private javax.swing.JLabel teacherGenderLabel;
    private javax.swing.JTextField teacherIdTextField;
    private javax.swing.JLabel teacherLastNameLabel;
    private javax.swing.JTextField teacherLastNameText;
    private javax.swing.JLabel teacherSelectLabel;
    private javax.swing.JButton teacherUpdateBtn;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
