/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class Management extends javax.swing.JPanel {

    /**
     * Creates new form Management
     */
    public Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        Teacher = new javax.swing.JPanel();
        teacherFirstNameText = new javax.swing.JTextField();
        teacherGender = new javax.swing.JComboBox<>();
        teacherContactLabel = new javax.swing.JLabel();
        teacherSelectLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        teacherIdTextField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        loadTeacherDataBtn = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        teacherUpdateBtn = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        teacherLastNameText = new javax.swing.JTextField();
        teacherEmailText = new javax.swing.JTextField();
        teacherAddressText = new javax.swing.JTextField();
        teacherContactText = new javax.swing.JTextField();
        teacherDepartmentLabel = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        teacherDepartment = new javax.swing.JComboBox<>();
        teacherFirstNameLabel = new javax.swing.JLabel();
        teacherLastNameLabel = new javax.swing.JLabel();
        teacherGenderLabel = new javax.swing.JLabel();
        teacherEmailLabel = new javax.swing.JLabel();
        teacherAddressLabel = new javax.swing.JLabel();
        Student = new javax.swing.JPanel();
        studentEmailLabel = new javax.swing.JLabel();
        studentAddressLabel = new javax.swing.JLabel();
        studentContactLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        studentLastNameText = new javax.swing.JTextField();
        studentEmailText = new javax.swing.JTextField();
        studentAddressText = new javax.swing.JTextField();
        studentContactText = new javax.swing.JTextField();
        studentCourseLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        studentBatchLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        studentCourseSelect = new javax.swing.JComboBox<>();
        studentBatchSelect = new javax.swing.JComboBox<>();
        studentFirstNameLabel = new javax.swing.JLabel();
        studentLastNameLabel = new javax.swing.JLabel();
        studentGenderLabel = new javax.swing.JLabel();
        studentFirstNameText = new javax.swing.JTextField();
        studentGenderSelect = new javax.swing.JComboBox<>();
        studentSelectLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        loadStudentDataBtn = new javax.swing.JButton();
        studentUpdateBtn = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        adminFirstNameLabel = new javax.swing.JLabel();
        adminLastNameLabel = new javax.swing.JLabel();
        adminFirstNameText = new javax.swing.JTextField();
        studentFirstNameText2 = new javax.swing.JTextField();
        adminGenderLabel = new javax.swing.JLabel();
        adminGenderSelect = new javax.swing.JComboBox<>();
        adminEmailLabel = new javax.swing.JLabel();
        adminEmailText = new javax.swing.JTextField();
        adminAddressLabel = new javax.swing.JLabel();
        adminAddressText = new javax.swing.JTextField();
        adminContactLabel = new javax.swing.JLabel();
        adminContactText = new javax.swing.JTextField();
        adminDepartmentLabel = new javax.swing.JLabel();
        adminDepartmentSelect = new javax.swing.JComboBox<>();
        adminUpdateBtn = new javax.swing.JButton();
        adminSelectLabel = new javax.swing.JLabel();
        adminIdTextField = new javax.swing.JTextField();
        loadAdminDataBtn = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        Course = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        courseContentPanel = new javax.swing.JPanel();
        updateCoursePanel = new javax.swing.JPanel();
        adminFirstNameLabel2 = new javax.swing.JLabel();
        adminFirstNameText2 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        courseSelectLabel = new javax.swing.JLabel();
        adminIdTextField1 = new javax.swing.JTextField();
        loadAdminDataBtn1 = new javax.swing.JButton();
        adminFirstNameLabel1 = new javax.swing.JLabel();
        adminFirstNameText1 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        loadAdminDataBtn2 = new javax.swing.JButton();
        loadAdminDataBtn3 = new javax.swing.JButton();
        addCoursePanel = new javax.swing.JPanel();
        courseSelectLabel1 = new javax.swing.JLabel();
        adminFirstNameText3 = new javax.swing.JTextField();
        adminFirstNameLabel3 = new javax.swing.JLabel();
        adminFirstNameText4 = new javax.swing.JTextField();
        adminFirstNameLabel4 = new javax.swing.JLabel();
        adminFirstNameText5 = new javax.swing.JTextField();
        adminFirstNameLabel5 = new javax.swing.JLabel();
        adminFirstNameText6 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        loadAdminDataBtn4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(910, 630));
        setMinimumSize(new java.awt.Dimension(910, 630));

        Teacher.setMaximumSize(new java.awt.Dimension(910, 608));
        Teacher.setMinimumSize(new java.awt.Dimension(910, 608));
        Teacher.setPreferredSize(new java.awt.Dimension(910, 608));

        teacherFirstNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherFirstNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherFirstNameText.addActionListener(this::teacherFirstNameTextActionPerformed);

        teacherGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
        teacherGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherGender.setFocusable(false);
        teacherGender.setOpaque(true);
        teacherGender.setRequestFocusEnabled(false);
        teacherGender.addActionListener(this::teacherGenderActionPerformed);

        teacherContactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherContactLabel.setText("Contact");

        teacherSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherSelectLabel.setText("Enter Teacher Id:");

        teacherIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        loadTeacherDataBtn.setBackground(new java.awt.Color(51, 51, 51));
        loadTeacherDataBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadTeacherDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        loadTeacherDataBtn.setText("Load Data");
        loadTeacherDataBtn.setFocusPainted(false);

        teacherUpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
        teacherUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        teacherUpdateBtn.setText("Update");
        teacherUpdateBtn.setFocusPainted(false);

        teacherLastNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherLastNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherEmailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherEmailText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherAddressText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherAddressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        teacherContactText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherContactText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teacherContactText.addActionListener(this::teacherContactTextActionPerformed);

        teacherDepartmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherDepartmentLabel.setText("Department");

        teacherDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentCourseSelect"
            + "" }));
teacherDepartment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
teacherDepartment.setFocusable(false);
teacherDepartment.setOpaque(true);
teacherDepartment.setRequestFocusEnabled(false);
teacherDepartment.addActionListener(this::teacherDepartmentActionPerformed);

teacherFirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherFirstNameLabel.setText("FIrst Name");

teacherLastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherLastNameLabel.setText("Last Name");

teacherGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherGenderLabel.setText("Gender");

teacherEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherEmailLabel.setText("Email");

teacherAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
teacherAddressLabel.setText("Address");

javax.swing.GroupLayout TeacherLayout = new javax.swing.GroupLayout(Teacher);
Teacher.setLayout(TeacherLayout);
TeacherLayout.setHorizontalGroup(
    TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(TeacherLayout.createSequentialGroup()
        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addComponent(teacherFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(314, 314, 314)
                            .addComponent(teacherLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(teacherAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(310, 310, 310)
                            .addComponent(teacherContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator10)
                                .addComponent(teacherLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(TeacherLayout.createSequentialGroup()
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TeacherLayout.createSequentialGroup()
                        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(teacherDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacherAddressText)
                            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacherDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TeacherLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherContactText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))))
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(teacherSelectLabel)
                .addGap(18, 18, 18)
                .addComponent(teacherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadTeacherDataBtn))
            .addGroup(TeacherLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(teacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(42, Short.MAX_VALUE))
    );
    TeacherLayout.setVerticalGroup(
        TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherSelectLabel)
                .addComponent(teacherIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadTeacherDataBtn))
            .addGap(30, 30, 30)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherFirstNameLabel)
                .addComponent(teacherLastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherGenderLabel)
                .addComponent(teacherEmailLabel))
            .addGap(12, 12, 12)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacherAddressLabel)
                .addGroup(TeacherLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(teacherContactLabel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(teacherContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(TeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(23, 23, 23)
            .addComponent(teacherDepartmentLabel)
            .addGap(3, 3, 3)
            .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addComponent(teacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(43, Short.MAX_VALUE))
    );

    tabbedPane.addTab("tab2", Teacher);

    Student.setBackground(new java.awt.Color(255, 255, 255));
    Student.setMaximumSize(new java.awt.Dimension(910, 608));
    Student.setMinimumSize(new java.awt.Dimension(910, 608));
    Student.setPreferredSize(new java.awt.Dimension(910, 608));

    studentEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailLabel.setText("Email");

    studentAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentAddressLabel.setText("Address");

    studentContactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentContactLabel.setText("Contact");

    studentLastNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentLastNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentEmailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentEmailText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentAddressText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentAddressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    studentContactText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentContactText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentContactText.addActionListener(this::studentContactTextActionPerformed);

    studentCourseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentCourseLabel.setText("Course");

    studentBatchLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentBatchLabel.setText("Batch");

    studentCourseSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentCourseSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentCourseSelect"
        + "" }));
studentCourseSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentCourseSelect.setFocusable(false);
studentCourseSelect.setOpaque(true);
studentCourseSelect.setRequestFocusEnabled(false);
studentCourseSelect.addActionListener(this::studentCourseSelectActionPerformed);

studentBatchSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentBatchSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a studentBatchSelect"
+ "" }));
studentBatchSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentBatchSelect.setFocusable(false);
studentBatchSelect.setOpaque(true);
studentBatchSelect.setRequestFocusEnabled(false);
studentBatchSelect.addActionListener(this::studentBatchSelectActionPerformed);

studentFirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentFirstNameLabel.setText("FIrst Name");

studentLastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentLastNameLabel.setText("Last Name");

studentGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentGenderLabel.setText("Gender");

studentFirstNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentFirstNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentFirstNameText.addActionListener(this::studentFirstNameTextActionPerformed);

studentGenderSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentGenderSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
studentGenderSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
studentGenderSelect.setFocusable(false);
studentGenderSelect.setOpaque(true);
studentGenderSelect.setRequestFocusEnabled(false);
studentGenderSelect.addActionListener(this::studentGenderSelectActionPerformed);

studentSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentSelectLabel.setText("Enter Student Id:");

studentIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

loadStudentDataBtn.setBackground(new java.awt.Color(51, 51, 51));
loadStudentDataBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
loadStudentDataBtn.setForeground(new java.awt.Color(255, 255, 255));
loadStudentDataBtn.setText("Load Data");
loadStudentDataBtn.setFocusPainted(false);

studentUpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
studentUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
studentUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
studentUpdateBtn.setText("Update");
studentUpdateBtn.setFocusPainted(false);

javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
Student.setLayout(StudentLayout);
StudentLayout.setHorizontalGroup(
    StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(StudentLayout.createSequentialGroup()
        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addComponent(studentFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(314, 314, 314)
                            .addComponent(studentLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(studentAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(310, 310, 310)
                            .addComponent(studentContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(studentLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(StudentLayout.createSequentialGroup()
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentCourseSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentAddressText)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentBatchSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, 384, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentBatchLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentContactText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)))))
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(studentSelectLabel)
                .addGap(18, 18, 18)
                .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadStudentDataBtn))
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(42, Short.MAX_VALUE))
    );
    StudentLayout.setVerticalGroup(
        StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentSelectLabel)
                .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadStudentDataBtn))
            .addGap(30, 30, 30)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentFirstNameLabel)
                .addComponent(studentLastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentGenderLabel)
                .addComponent(studentEmailLabel))
            .addGap(12, 12, 12)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentAddressLabel)
                .addGroup(StudentLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(studentContactLabel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
                    .addComponent(studentCourseLabel)
                    .addGap(3, 3, 3)
                    .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentCourseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentBatchSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLayout.createSequentialGroup()
                    .addComponent(studentBatchLabel)
                    .addGap(51, 51, 51)))
            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(studentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(45, Short.MAX_VALUE))
    );

    tabbedPane.addTab("tab1", Student);

    Admin.setMaximumSize(new java.awt.Dimension(910, 608));
    Admin.setMinimumSize(new java.awt.Dimension(910, 608));
    Admin.setPreferredSize(new java.awt.Dimension(910, 608));

    adminFirstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel.setText("FIrst Name");

    adminLastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminLastNameLabel.setText("Last Name");

    adminFirstNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    adminFirstNameText.addActionListener(this::adminFirstNameTextActionPerformed);

    studentFirstNameText2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    studentFirstNameText2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    studentFirstNameText2.addActionListener(this::studentFirstNameText2ActionPerformed);

    adminGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminGenderLabel.setText("Gender");

    adminGenderSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminGenderSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
    adminGenderSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    adminGenderSelect.setFocusable(false);
    adminGenderSelect.setOpaque(true);
    adminGenderSelect.setRequestFocusEnabled(false);
    adminGenderSelect.addActionListener(this::adminGenderSelectActionPerformed);

    adminEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminEmailLabel.setText("Email");

    adminEmailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminEmailText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminAddressLabel.setText("Address");

    adminAddressText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminAddressText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminContactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminContactLabel.setText("Contact");

    adminContactText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminContactText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    adminContactText.addActionListener(this::adminContactTextActionPerformed);

    adminDepartmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminDepartmentLabel.setText("Department");

    adminDepartmentSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminDepartmentSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female","Other" }));
    adminDepartmentSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    adminDepartmentSelect.setFocusable(false);
    adminDepartmentSelect.setOpaque(true);
    adminDepartmentSelect.setRequestFocusEnabled(false);
    adminDepartmentSelect.addActionListener(this::adminDepartmentSelectActionPerformed);

    adminUpdateBtn.setBackground(new java.awt.Color(0, 0, 0));
    adminUpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
    adminUpdateBtn.setText("Update");
    adminUpdateBtn.addActionListener(this::adminUpdateBtnActionPerformed);

    adminSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminSelectLabel.setText("Enter Admin Id:");

    adminIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    loadAdminDataBtn.setBackground(new java.awt.Color(51, 51, 51));
    loadAdminDataBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadAdminDataBtn.setForeground(new java.awt.Color(255, 255, 255));
    loadAdminDataBtn.setText("Load Data");
    loadAdminDataBtn.setFocusPainted(false);

    javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
    Admin.setLayout(AdminLayout);
    AdminLayout.setHorizontalGroup(
        AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AdminLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(adminFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminDepartmentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(109, 109, 109)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(adminContactText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentFirstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(adminSelectLabel)
                    .addGap(18, 18, 18)
                    .addComponent(adminIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(loadAdminDataBtn)))
            .addContainerGap(14, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(adminUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(366, 366, 366))
    );
    AdminLayout.setVerticalGroup(
        AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AdminLayout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminSelectLabel)
                .addComponent(adminIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadAdminDataBtn))
            .addGap(34, 34, 34)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminFirstNameLabel)
                .addComponent(adminLastNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(studentFirstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminGenderLabel)
                        .addComponent(adminEmailLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminGenderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminAddressLabel)
                        .addComponent(adminContactLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24)
            .addComponent(adminDepartmentLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(adminDepartmentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
            .addComponent(adminUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(87, 87, 87))
    );

    tabbedPane.addTab("tab3", Admin);

    Course.setMaximumSize(new java.awt.Dimension(910, 608));
    Course.setMinimumSize(new java.awt.Dimension(910, 608));
    Course.setPreferredSize(new java.awt.Dimension(910, 608));

    jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add A New Course", "Update Course" }));

    courseContentPanel.setLayout(new java.awt.CardLayout());

    updateCoursePanel.setMaximumSize(new java.awt.Dimension(859, 450));
    updateCoursePanel.setMinimumSize(new java.awt.Dimension(859, 450));

    adminFirstNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel2.setText("Course Duration");

    adminFirstNameText2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    courseSelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    courseSelectLabel.setText("Enter Course Id:");

    adminIdTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    loadAdminDataBtn1.setBackground(new java.awt.Color(51, 51, 51));
    loadAdminDataBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadAdminDataBtn1.setForeground(new java.awt.Color(255, 255, 255));
    loadAdminDataBtn1.setText("Update");
    loadAdminDataBtn1.setFocusPainted(false);
    loadAdminDataBtn1.addActionListener(this::loadAdminDataBtn1ActionPerformed);

    adminFirstNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel1.setText("Course Name");

    adminFirstNameText1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    loadAdminDataBtn2.setBackground(new java.awt.Color(182, 51, 51));
    loadAdminDataBtn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadAdminDataBtn2.setForeground(new java.awt.Color(255, 255, 255));
    loadAdminDataBtn2.setText("Delete");
    loadAdminDataBtn2.setFocusPainted(false);

    loadAdminDataBtn3.setBackground(new java.awt.Color(51, 51, 51));
    loadAdminDataBtn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadAdminDataBtn3.setForeground(new java.awt.Color(255, 255, 255));
    loadAdminDataBtn3.setText("Load Data");
    loadAdminDataBtn3.setFocusPainted(false);

    javax.swing.GroupLayout updateCoursePanelLayout = new javax.swing.GroupLayout(updateCoursePanel);
    updateCoursePanel.setLayout(updateCoursePanelLayout);
    updateCoursePanelLayout.setHorizontalGroup(
        updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(updateCoursePanelLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminFirstNameLabel1)
                .addGroup(updateCoursePanelLayout.createSequentialGroup()
                    .addComponent(courseSelectLabel)
                    .addGap(18, 18, 18)
                    .addComponent(adminFirstNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(loadAdminDataBtn3))
                .addComponent(adminFirstNameLabel2)
                .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminFirstNameText2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(adminIdTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(updateCoursePanelLayout.createSequentialGroup()
                    .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(updateCoursePanelLayout.createSequentialGroup()
                            .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateCoursePanelLayout.createSequentialGroup()
                            .addComponent(loadAdminDataBtn1)
                            .addGap(72, 72, 72)))
                    .addComponent(loadAdminDataBtn2)))
            .addContainerGap(283, Short.MAX_VALUE))
    );
    updateCoursePanelLayout.setVerticalGroup(
        updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(updateCoursePanelLayout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(courseSelectLabel)
                .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminFirstNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadAdminDataBtn3)))
            .addGap(64, 64, 64)
            .addComponent(adminFirstNameLabel1)
            .addGap(4, 4, 4)
            .addComponent(adminIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
            .addComponent(adminFirstNameLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(adminFirstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
            .addGroup(updateCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loadAdminDataBtn1)
                .addComponent(loadAdminDataBtn2))
            .addGap(40, 40, 40))
    );

    courseContentPanel.add(updateCoursePanel, "card3");

    addCoursePanel.setMaximumSize(new java.awt.Dimension(859, 450));
    addCoursePanel.setMinimumSize(new java.awt.Dimension(859, 450));
    addCoursePanel.setPreferredSize(new java.awt.Dimension(859, 450));

    courseSelectLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    courseSelectLabel1.setText("Enter Course Id:");

    adminFirstNameText3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminFirstNameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel3.setText("Course Name");

    adminFirstNameText4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminFirstNameLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel4.setText("Course Duration");

    adminFirstNameText5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

    adminFirstNameLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameLabel5.setText("Enter Departmetn Id:");

    adminFirstNameText6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    adminFirstNameText6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    adminFirstNameText6.addActionListener(this::adminFirstNameText6ActionPerformed);

    loadAdminDataBtn4.setBackground(new java.awt.Color(51, 178, 66));
    loadAdminDataBtn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    loadAdminDataBtn4.setForeground(new java.awt.Color(255, 255, 255));
    loadAdminDataBtn4.setText("Add");
    loadAdminDataBtn4.setFocusPainted(false);
    loadAdminDataBtn4.addActionListener(this::loadAdminDataBtn4ActionPerformed);

    javax.swing.GroupLayout addCoursePanelLayout = new javax.swing.GroupLayout(addCoursePanel);
    addCoursePanel.setLayout(addCoursePanelLayout);
    addCoursePanelLayout.setHorizontalGroup(
        addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addCoursePanelLayout.createSequentialGroup()
            .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addCoursePanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adminFirstNameLabel4)
                        .addComponent(adminFirstNameLabel3)
                        .addComponent(adminFirstNameText4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addComponent(adminFirstNameText5)
                        .addComponent(jSeparator26)
                        .addComponent(jSeparator27)))
                .addGroup(addCoursePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(adminFirstNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(courseSelectLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adminFirstNameText3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(adminFirstNameText6))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCoursePanelLayout.createSequentialGroup()
            .addGap(0, 385, Short.MAX_VALUE)
            .addComponent(loadAdminDataBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(339, 339, 339))
    );
    addCoursePanelLayout.setVerticalGroup(
        addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addCoursePanelLayout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(courseSelectLabel1)
                .addComponent(adminFirstNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(addCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminFirstNameLabel5)
                .addComponent(adminFirstNameText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(56, 56, 56)
            .addComponent(adminFirstNameLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(adminFirstNameText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(43, 43, 43)
            .addComponent(adminFirstNameLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(adminFirstNameText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addComponent(loadAdminDataBtn4)
            .addGap(32, 32, 32))
    );

    courseContentPanel.add(addCoursePanel, "card2");

    javax.swing.GroupLayout CourseLayout = new javax.swing.GroupLayout(Course);
    Course.setLayout(CourseLayout);
    CourseLayout.setHorizontalGroup(
        CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CourseLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(courseContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(25, 25, 25))
    );
    CourseLayout.setVerticalGroup(
        CourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CourseLayout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
            .addComponent(courseContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    tabbedPane.addTab("tab4", Course);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabbedPane)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabbedPane)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void studentCourseSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCourseSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentCourseSelectActionPerformed

    private void studentBatchSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBatchSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentBatchSelectActionPerformed

    private void studentFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFirstNameTextActionPerformed

    private void studentGenderSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGenderSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentGenderSelectActionPerformed

    private void studentContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentContactTextActionPerformed

    private void teacherFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherFirstNameTextActionPerformed

    private void teacherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherGenderActionPerformed

    private void teacherContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherContactTextActionPerformed

    private void teacherDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherDepartmentActionPerformed

    private void studentFirstNameText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFirstNameText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFirstNameText2ActionPerformed

    private void adminFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminFirstNameTextActionPerformed

    private void adminGenderSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGenderSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminGenderSelectActionPerformed

    private void adminDepartmentSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDepartmentSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminDepartmentSelectActionPerformed

    private void adminUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUpdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUpdateBtnActionPerformed

    private void adminContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminContactTextActionPerformed

    private void loadAdminDataBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadAdminDataBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadAdminDataBtn1ActionPerformed

    private void adminFirstNameText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFirstNameText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminFirstNameText6ActionPerformed

    private void loadAdminDataBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadAdminDataBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadAdminDataBtn4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JPanel Course;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel Teacher;
    private javax.swing.JPanel addCoursePanel;
    private javax.swing.JLabel adminAddressLabel;
    private javax.swing.JTextField adminAddressText;
    private javax.swing.JLabel adminContactLabel;
    private javax.swing.JTextField adminContactText;
    private javax.swing.JLabel adminDepartmentLabel;
    private javax.swing.JComboBox<String> adminDepartmentSelect;
    private javax.swing.JLabel adminEmailLabel;
    private javax.swing.JTextField adminEmailText;
    private javax.swing.JLabel adminFirstNameLabel;
    private javax.swing.JLabel adminFirstNameLabel1;
    private javax.swing.JLabel adminFirstNameLabel2;
    private javax.swing.JLabel adminFirstNameLabel3;
    private javax.swing.JLabel adminFirstNameLabel4;
    private javax.swing.JLabel adminFirstNameLabel5;
    private javax.swing.JTextField adminFirstNameText;
    private javax.swing.JTextField adminFirstNameText1;
    private javax.swing.JTextField adminFirstNameText2;
    private javax.swing.JTextField adminFirstNameText3;
    private javax.swing.JTextField adminFirstNameText4;
    private javax.swing.JTextField adminFirstNameText5;
    private javax.swing.JTextField adminFirstNameText6;
    private javax.swing.JLabel adminGenderLabel;
    private javax.swing.JComboBox<String> adminGenderSelect;
    private javax.swing.JTextField adminIdTextField;
    private javax.swing.JTextField adminIdTextField1;
    private javax.swing.JLabel adminLastNameLabel;
    private javax.swing.JLabel adminSelectLabel;
    private javax.swing.JButton adminUpdateBtn;
    private javax.swing.JPanel courseContentPanel;
    private javax.swing.JLabel courseSelectLabel;
    private javax.swing.JLabel courseSelectLabel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton loadAdminDataBtn;
    private javax.swing.JButton loadAdminDataBtn1;
    private javax.swing.JButton loadAdminDataBtn2;
    private javax.swing.JButton loadAdminDataBtn3;
    private javax.swing.JButton loadAdminDataBtn4;
    private javax.swing.JButton loadStudentDataBtn;
    private javax.swing.JButton loadTeacherDataBtn;
    private javax.swing.JLabel studentAddressLabel;
    private javax.swing.JTextField studentAddressText;
    private javax.swing.JLabel studentBatchLabel;
    private javax.swing.JComboBox<String> studentBatchSelect;
    private javax.swing.JLabel studentContactLabel;
    private javax.swing.JTextField studentContactText;
    private javax.swing.JLabel studentCourseLabel;
    private javax.swing.JComboBox<String> studentCourseSelect;
    private javax.swing.JLabel studentEmailLabel;
    private javax.swing.JTextField studentEmailText;
    private javax.swing.JLabel studentFirstNameLabel;
    private javax.swing.JTextField studentFirstNameText;
    private javax.swing.JTextField studentFirstNameText2;
    private javax.swing.JLabel studentGenderLabel;
    private javax.swing.JComboBox<String> studentGenderSelect;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JLabel studentLastNameLabel;
    private javax.swing.JTextField studentLastNameText;
    private javax.swing.JLabel studentSelectLabel;
    private javax.swing.JButton studentUpdateBtn;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel teacherAddressLabel;
    private javax.swing.JTextField teacherAddressText;
    private javax.swing.JLabel teacherContactLabel;
    private javax.swing.JTextField teacherContactText;
    private javax.swing.JComboBox<String> teacherDepartment;
    private javax.swing.JLabel teacherDepartmentLabel;
    private javax.swing.JLabel teacherEmailLabel;
    private javax.swing.JTextField teacherEmailText;
    private javax.swing.JLabel teacherFirstNameLabel;
    private javax.swing.JTextField teacherFirstNameText;
    private javax.swing.JComboBox<String> teacherGender;
    private javax.swing.JLabel teacherGenderLabel;
    private javax.swing.JTextField teacherIdTextField;
    private javax.swing.JLabel teacherLastNameLabel;
    private javax.swing.JTextField teacherLastNameText;
    private javax.swing.JLabel teacherSelectLabel;
    private javax.swing.JButton teacherUpdateBtn;
    private javax.swing.JPanel updateCoursePanel;
    // End of variables declaration//GEN-END:variables
}
