/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class moduleContainerPanel extends javax.swing.JPanel {

    /**
     * Creates new form moduleContainerPanel
     */
    public moduleContainerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleName = new javax.swing.JLabel();
        moduleYear = new javax.swing.JLabel();
        actionBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(890, 65));
        setMinimumSize(new java.awt.Dimension(890, 65));
        setPreferredSize(new java.awt.Dimension(890, 65));

        moduleName.setBackground(new java.awt.Color(255, 255, 255));
        moduleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleName.setText("  'jLabel1");
        moduleName.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        moduleName.setMaximumSize(new java.awt.Dimension(290, 65));
        moduleName.setMinimumSize(new java.awt.Dimension(290, 65));
        moduleName.setOpaque(true);
        moduleName.setPreferredSize(new java.awt.Dimension(295, 65));

        moduleYear.setBackground(new java.awt.Color(255, 255, 255));
        moduleYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleYear.setText("  'jLabel1");
        moduleYear.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        moduleYear.setMaximumSize(new java.awt.Dimension(290, 65));
        moduleYear.setMinimumSize(new java.awt.Dimension(290, 65));
        moduleYear.setOpaque(true);
        moduleYear.setPreferredSize(new java.awt.Dimension(295, 65));

        actionBtn.setBackground(new java.awt.Color(62, 126, 171));
        actionBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actionBtn.setForeground(new java.awt.Color(0, 51, 255));
        actionBtn.setText("Go To  Module");
        actionBtn.setBorder(null);
        actionBtn.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(actionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moduleName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(actionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionBtn;
    private javax.swing.JLabel moduleName;
    private javax.swing.JLabel moduleYear;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getModuleName(){
   return moduleName;
}
public javax.swing.JLabel getModuleYear(){
   return moduleYear;
}
}
