/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class ModuleDisplay extends javax.swing.JPanel {

    /**
     * Creates new form moduleDisplay
     */
    public ModuleDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moduleName = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        chapters = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        chapterComboBox = new javax.swing.JComboBox<>();
        moduleDisplayPort = new javax.swing.JScrollPane();

        setMaximumSize(new java.awt.Dimension(910, 630));
        setMinimumSize(new java.awt.Dimension(910, 630));

        jPanel1.setBackground(new java.awt.Color(19, 165, 114));
        jPanel1.setMaximumSize(new java.awt.Dimension(660, 135));
        jPanel1.setMinimumSize(new java.awt.Dimension(660, 135));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 135));

        moduleName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moduleName.setText("Module Name");

        year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        year.setText("Year:");

        chapters.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapters.setText("Chapters:");

        duration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration.setText("Duration:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(moduleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(chapters, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duration, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(chapters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        chapterComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addComponent(moduleDisplayPort)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chapterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(chapterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moduleDisplayPort, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chapterComboBox;
    private javax.swing.JLabel chapters;
    private javax.swing.JLabel duration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane moduleDisplayPort;
    private javax.swing.JLabel moduleName;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables

    public void addChapterComboBoxActionListener(ActionListener actionListener)
    {
        chapterComboBox.addActionListener(actionListener);
    }

    public javax.swing.JScrollPane getModuleDisplayPort()
    {
    return moduleDisplayPort;
    }

    public javax.swing.JComboBox<String> getChapterComboBox()
    {
        return chapterComboBox;
    }

    public void setModuleName(String name)
    {
        moduleName.setText(name);
    }

    public void setChapters(int size)
    {
        chapters.setText("Chapters:"+size);
    }

    public void setDuration(int length)
    {
        duration.setText("Duration:"+length);
    }
     public void setYear(int year){
        this.year.setText("Year:"+year);

     }
}
