/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class moduleContainerPanel extends javax.swing.JPanel {

    /**
     * Creates new form moduleContainerPanel
     */
    public moduleContainerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleName = new javax.swing.JLabel();
        moduleAction = new javax.swing.JButton();
        moduleYear = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(860, 65));
        setMinimumSize(new java.awt.Dimension(860, 65));
        setPreferredSize(new java.awt.Dimension(860, 65));

        moduleName.setBackground(new java.awt.Color(255, 255, 255));
        moduleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleName.setForeground(new java.awt.Color(0, 0, 0));
        moduleName.setText("jLabel2");
        moduleName.setOpaque(true);

        moduleAction.setBackground(new java.awt.Color(2, 95, 255));
        moduleAction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleAction.setText("Go To Module Content");
        moduleAction.setFocusPainted(false);
        moduleAction.setMaximumSize(new java.awt.Dimension(258, 64));
        moduleAction.setMinimumSize(new java.awt.Dimension(258, 64));
        moduleAction.setOpaque(true);
        moduleAction.setPreferredSize(new java.awt.Dimension(258, 64));
        moduleAction.addActionListener(this::moduleActionActionPerformed);

        moduleYear.setBackground(new java.awt.Color(255, 255, 255));
        moduleYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleYear.setForeground(new java.awt.Color(0, 0, 0));
        moduleYear.setText("jLabel1");
        moduleYear.setMaximumSize(new java.awt.Dimension(257, 64));
        moduleYear.setMinimumSize(new java.awt.Dimension(257, 64));
        moduleYear.setOpaque(true);
        moduleYear.setPreferredSize(new java.awt.Dimension(257, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(moduleAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moduleName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void moduleActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton moduleAction;
    private javax.swing.JLabel moduleName;
    private javax.swing.JLabel moduleYear;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getModuleName()
    {
        return moduleName;
    }

    public javax.swing.JLabel getModuleYear()
    {
        return moduleYear;
    }

    public void addAddModuleActionListener(ActionListener actionListener)
    {
        moduleAction.addActionListener(actionListener);
    }


}
