/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class NewBatchPopUp extends javax.swing.JPanel {

    /**
     * Creates new form NewCoursePopUp
     */
    public NewBatchPopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCourseNameLabel = new javax.swing.JLabel();
        newBatchNameTextField = new javax.swing.JTextField();
        newBatchSectionTextField = new javax.swing.JTextField();
        newCourseDurationLabel = new javax.swing.JLabel();
        batchAddBtn = new javax.swing.JButton();

        newCourseNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newCourseNameLabel.setText("BatchName:");

        newBatchNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newBatchNameTextField.addActionListener(this::newBatchNameTextFieldActionPerformed);

        newBatchSectionTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        newCourseDurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newCourseDurationLabel.setText("Section");

        batchAddBtn.setBackground(new java.awt.Color(0, 0, 0));
        batchAddBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        batchAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        batchAddBtn.setText("Add");
        batchAddBtn.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCourseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newBatchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCourseDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBatchSectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(batchAddBtn)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCourseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBatchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCourseDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBatchSectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(batchAddBtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newBatchNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBatchNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBatchNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchAddBtn;
    private javax.swing.JTextField newBatchNameTextField;
    private javax.swing.JTextField newBatchSectionTextField;
    private javax.swing.JLabel newCourseDurationLabel;
    private javax.swing.JLabel newCourseNameLabel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getBatchNameTextField() {
        return newBatchNameTextField;
    }

    public javax.swing.JTextField getBatchSectionTextField() {
        return newBatchSectionTextField;
    }

    public void addBatchAddBtnActionListener(ActionListener actionListener){batchAddBtn.addActionListener(actionListener);}
}
