/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class NewChapterPopUp extends javax.swing.JPanel {

    /**
     * Creates new form newChapterPopUp
     */
    public NewChapterPopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chapterNameLabel = new javax.swing.JLabel();
        chapterName = new javax.swing.JTextField();
        chapterPdfLabel = new javax.swing.JLabel();
        chapterPdf = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        chapterNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapterNameLabel.setText("ChapterName:");

        chapterName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapterName.addActionListener(this::chapterNameActionPerformed);

        chapterPdfLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapterPdfLabel.setText("Chapter Pdf   :");

        chapterPdf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chapterPdf.setText("Add Chapter Pdf");
        chapterPdf.addActionListener(this::chapterPdfActionPerformed);

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(this::addBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chapterNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(chapterPdfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chapterName, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addComponent(chapterPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chapterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chapterName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chapterPdfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chapterPdf))
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chapterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chapterNameActionPerformed

    private void chapterPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapterPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chapterPdfActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField chapterName;
    private javax.swing.JLabel chapterNameLabel;
    private javax.swing.JButton chapterPdf;
    private javax.swing.JLabel chapterPdfLabel;
    // End of variables declaration//GEN-END:variables

    public JTextField getChapterName(){return chapterName;}
    public JButton getChapterPdf(){return chapterPdf;}
    public void addChapterPdfActionListener(ActionListener actionListener){chapterPdf.addActionListener(actionListener);}
    public void addAddBtnActionListener(ActionListener actionListener){addBtn.addActionListener(actionListener);}
}
