/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class NewCoursePopUp extends javax.swing.JPanel {

    /**
     * Creates new form NewCoursePopUp
     */
    public NewCoursePopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCourseNameLabel = new javax.swing.JLabel();
        newCourseNameTextField = new javax.swing.JTextField();
        newCourseDurationTextField = new javax.swing.JTextField();
        newCourseDurationLabel = new javax.swing.JLabel();
        courseAddBtn = new javax.swing.JButton();

        newCourseNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newCourseNameLabel.setText("CourseName:");

        newCourseNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newCourseNameTextField.addActionListener(this::newCourseNameTextFieldActionPerformed);

        newCourseDurationTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        newCourseDurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newCourseDurationLabel.setText("Duration:");

        courseAddBtn.setBackground(new java.awt.Color(0, 0, 0));
        courseAddBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        courseAddBtn.setText("Add");
        courseAddBtn.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCourseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCourseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCourseDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newCourseDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courseAddBtn)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCourseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCourseDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(courseAddBtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newCourseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseAddBtn;
    private javax.swing.JLabel newCourseDurationLabel;
    private javax.swing.JTextField newCourseDurationTextField;
    private javax.swing.JLabel newCourseNameLabel;
    private javax.swing.JTextField newCourseNameTextField;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getCourseNameTextField() {
        return newCourseNameTextField;
    }

    public javax.swing.JTextField getCourseDurationTextField() {
        return newCourseDurationTextField;
    }

    public void addCourseAddBtnActionListener(ActionListener actionListener){courseAddBtn.addActionListener(actionListener);}
}
