/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class OtpVerification extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OtpVerification.class.getName());

    /**
     * Creates new form OtpVerification
     */
    public OtpVerification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        otpPanel = new javax.swing.JPanel();
        authenticate = new javax.swing.JLabel();
        verifyButton = new javax.swing.JButton();
        optText = new javax.swing.JLabel();
        o1 = new javax.swing.JTextField();
        o3 = new javax.swing.JTextField();
        o4 = new javax.swing.JTextField();
        o5 = new javax.swing.JTextField();
        o6 = new javax.swing.JTextField();
        uthenticatIcon = new javax.swing.JLabel();
        o2 = new javax.swing.JTextField();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 630));

        Body.setMinimumSize(new java.awt.Dimension(1120, 630));
        Body.setLayout(null);

        otpPanel.setBackground(new java.awt.Color(220, 220, 210));
        otpPanel.setForeground(new java.awt.Color(255, 255, 255));
        otpPanel.setMinimumSize(new java.awt.Dimension(390, 430));

        authenticate.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        authenticate.setForeground(new java.awt.Color(0, 0, 0));
        authenticate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authenticate.setText("Authenticate");
        authenticate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        authenticate.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        verifyButton.setBackground(new java.awt.Color(0, 0, 0));
        verifyButton.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        verifyButton.setForeground(new java.awt.Color(255, 255, 255));
        verifyButton.setText("Verify");

        optText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        optText.setForeground(new java.awt.Color(0, 0, 0));
        optText.setText("Enter the OTP that was sent to your device");

        o1.setBackground(new java.awt.Color(255, 255, 255));
        o1.setForeground(new java.awt.Color(0, 0, 0));

        o3.setBackground(new java.awt.Color(255, 255, 255));
        o3.setForeground(new java.awt.Color(0, 0, 0));

        o4.setBackground(new java.awt.Color(255, 255, 255));
        o4.setForeground(new java.awt.Color(0, 0, 0));

        o5.setBackground(new java.awt.Color(255, 255, 255));
        o5.setForeground(new java.awt.Color(0, 0, 0));

        o6.setBackground(new java.awt.Color(255, 255, 255));
        o6.setForeground(new java.awt.Color(0, 0, 0));

        uthenticatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otp.png"))); // NOI18N
        uthenticatIcon.setText("jLabel3");

        o2.setBackground(new java.awt.Color(255, 255, 255));
        o2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout otpPanelLayout = new javax.swing.GroupLayout(otpPanel);
        otpPanel.setLayout(otpPanelLayout);
        otpPanelLayout.setHorizontalGroup(
            otpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otpPanelLayout.createSequentialGroup()
                .addGroup(otpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otpPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(otpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(otpPanelLayout.createSequentialGroup()
                                .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(optText, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(otpPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otpPanelLayout.createSequentialGroup()
                .addComponent(authenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otpPanelLayout.createSequentialGroup()
                .addComponent(uthenticatIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        otpPanelLayout.setVerticalGroup(
            otpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otpPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(uthenticatIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(otpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Body.add(otpPanel);
        otpPanel.setBounds(130, 90, 390, 420);

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logInBg.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        Body.add(bgImage);
        bgImage.setBounds(0, 0, 1120, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OtpVerification().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel authenticate;
    private javax.swing.JLabel bgImage;
    private javax.swing.JTextField o1;
    private javax.swing.JTextField o2;
    private javax.swing.JTextField o3;
    private javax.swing.JTextField o4;
    private javax.swing.JTextField o5;
    private javax.swing.JTextField o6;
    private javax.swing.JLabel optText;
    private javax.swing.JPanel otpPanel;
    private javax.swing.JLabel uthenticatIcon;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
    public int getOtp()
    {
        String password = o1.getText()+o1.getText()+o1.getText()+o3.getText()+o4.getText()+o5.getText()+o6.getText();
        return Integer.parseInt(password);
    }
    public void addVerifyButtonActionListener(ActionListener actionListener)
    {
        verifyButton.addActionListener(actionListener);
    }




}
