/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class STModulePanel extends javax.swing.JPanel {

    /**
     * Creates new form STModulePanel
     */
    public STModulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleHomePage = new javax.swing.JPanel();
        moduleName = new javax.swing.JLabel();
        moduleYear = new javax.swing.JLabel();
        action = new javax.swing.JLabel();
        moduleScrollPane = new javax.swing.JScrollPane();
        moduleContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(910, 630));
        setMinimumSize(new java.awt.Dimension(910, 630));
        setLayout(new java.awt.CardLayout());

        moduleHomePage.setBackground(new java.awt.Color(255, 255, 255));
        moduleHomePage.setMinimumSize(new java.awt.Dimension(910, 630));
        moduleHomePage.setPreferredSize(new java.awt.Dimension(910, 630));

        moduleName.setBackground(new java.awt.Color(255, 51, 51));
        moduleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleName.setText("  Module Name");
        moduleName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        moduleName.setMaximumSize(new java.awt.Dimension(290, 40));
        moduleName.setMinimumSize(new java.awt.Dimension(290, 40));
        moduleName.setOpaque(true);
        moduleName.setPreferredSize(new java.awt.Dimension(290, 40));

        moduleYear.setBackground(new java.awt.Color(255, 51, 51));
        moduleYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moduleYear.setText(" Year");
        moduleYear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        moduleYear.setOpaque(true);

        action.setBackground(new java.awt.Color(255, 51, 51));
        action.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        action.setText("Action");
        action.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        action.setOpaque(true);

        moduleScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        moduleScrollPane.setPreferredSize(new java.awt.Dimension(890, 450));

        moduleContainer.setBackground(new java.awt.Color(255, 255, 255));
        moduleContainer.setMaximumSize(new java.awt.Dimension(890, 1320));
        moduleContainer.setMinimumSize(new java.awt.Dimension(890, 1320));
        moduleContainer.setPreferredSize(new java.awt.Dimension(890, 1320));
        moduleContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 1));
        moduleScrollPane.setViewportView(moduleContainer);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 0, 98));
        jLabel1.setText("My Modules");

        javax.swing.GroupLayout moduleHomePageLayout = new javax.swing.GroupLayout(moduleHomePage);
        moduleHomePage.setLayout(moduleHomePageLayout);
        moduleHomePageLayout.setHorizontalGroup(
            moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleHomePageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(moduleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(moduleHomePageLayout.createSequentialGroup()
                            .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(moduleYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0)
                            .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))))
                .addGap(15, 15, 15))
        );
        moduleHomePageLayout.setVerticalGroup(
            moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleHomePageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moduleHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(moduleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(moduleHomePage, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel moduleContainer;
    private javax.swing.JPanel moduleHomePage;
    private javax.swing.JLabel moduleName;
    private javax.swing.JScrollPane moduleScrollPane;
    private javax.swing.JLabel moduleYear;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JPanel getModuleContainer()
    {
    return moduleContainer;
    }
}
