/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author subas
 */
public class StudentAttendanceContainer extends javax.swing.JPanel {

    /**
     * Creates new form StudentAttendanceContainer
     */
    public StudentAttendanceContainer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        percentage = new javax.swing.JLabel();
        moduleName = new javax.swing.JLabel();
        absentLabel = new javax.swing.JLabel();
        presentLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(100, 217, 156));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(273, 150));
        setMinimumSize(new java.awt.Dimension(273, 150));
        setPreferredSize(new java.awt.Dimension(273, 155));

        percentage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        percentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentage.setText("100%");

        moduleName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduleName.setText("Module Name");

        absentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        absentLabel.setText("Absent:");
        absentLabel.setMaximumSize(new java.awt.Dimension(131, 48));
        absentLabel.setMinimumSize(new java.awt.Dimension(131, 48));
        absentLabel.setPreferredSize(new java.awt.Dimension(131, 48));

        presentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        presentLabel.setText("Present: ");
        presentLabel.setMaximumSize(new java.awt.Dimension(131, 48));
        presentLabel.setMinimumSize(new java.awt.Dimension(131, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(absentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(absentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentLabel;
    private javax.swing.JLabel moduleName;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel presentLabel;
    // End of variables declaration//GEN-END:variables

    public void setModuleName(String name){moduleName.setText( name);}

    public void setPresentLabel(int presentDays){presentLabel.setText("Present :"+ presentDays);}


    public void setAbsentLabel(int absentDays){absentLabel.setText("Absent :"+ absentDays);}

    public void setPercentage(double percentageText){percentage.setText(String.format("%.2f", percentageText)+"%");}


}
