/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.TableActionEvent;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author subas
 */
public class TablePanelAction extends javax.swing.JPanel {

    /**
     * Creates new form TablePanelAction
     */
    public TablePanelAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateBatch = new javax.swing.JButton();
        deleteBatch = new javax.swing.JButton();

        updateBatch.setBackground(new java.awt.Color(0, 0, 0));
        updateBatch.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        updateBatch.setForeground(new java.awt.Color(255, 255, 255));
        updateBatch.setText("Update");
        updateBatch.addActionListener(this::updateBatchActionPerformed);

        deleteBatch.setBackground(new java.awt.Color(147, 0, 26));
        deleteBatch.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        deleteBatch.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(updateBatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBatch)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBatch)
                    .addComponent(deleteBatch))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBatch;
    private javax.swing.JButton updateBatch;
    // End of variables declaration//GEN-END:variables

    public void addTableRowActionListener(TableActionEvent event, JTable jtable)
    {
      deleteBatch.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
              int row = jtable.getEditingRow();
              event.onDelete(row);
          }
      });

      updateBatch.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {

              int row = jtable.getEditingRow();
              event.onUpdate(row);
          }
      });

    }
}
